CT_SEG_FILE_LIST = [
    'adrenal_gland_left.nii.gz',
    'adrenal_gland_right.nii.gz',
    'aorta.nii.gz',
    'atrial_appendage_left.nii.gz',
    'autochthon_left.nii.gz',
    'autochthon_right.nii.gz',
    'brachiocephalic_trunk.nii.gz',
    'brachiocephalic_vein_left.nii.gz',
    'brachiocephalic_vein_right.nii.gz',
    'brain.nii.gz',
    'clavicula_left.nii.gz',
    'clavicula_right.nii.gz',
    'colon.nii.gz',
    'common_carotid_artery_left.nii.gz',
    'common_carotid_artery_right.nii.gz',
    'costal_cartilages.nii.gz',
    'duodenum.nii.gz',
    'esophagus.nii.gz',
    'femur_left.nii.gz',
    'femur_right.nii.gz',
    'gallbladder.nii.gz',
    'gluteus_maximus_left.nii.gz',
    'gluteus_maximus_right.nii.gz',
    'gluteus_medius_left.nii.gz',
    'gluteus_medius_right.nii.gz',
    'gluteus_minimus_left.nii.gz',
    'gluteus_minimus_right.nii.gz',
    'heart.nii.gz',
    'hip_left.nii.gz',
    'hip_right.nii.gz',
    'humerus_left.nii.gz',
    'humerus_right.nii.gz',
    'iliac_artery_left.nii.gz',
    'iliac_artery_right.nii.gz',
    'iliac_vena_left.nii.gz',
    'iliac_vena_right.nii.gz',
    'iliopsoas_left.nii.gz',
    'iliopsoas_right.nii.gz',
    'inferior_vena_cava.nii.gz',
    'sacrum.nii.gz',
    'kidney_cyst_left.nii.gz',
    'kidney_cyst_right.nii.gz',
    'kidney_left.nii.gz',
    'kidney_right.nii.gz',
    'liver.nii.gz',
    'lung_lower_lobe_left.nii.gz',
    'lung_lower_lobe_right.nii.gz',
    'lung_middle_lobe_right.nii.gz',
    'lung_upper_lobe_left.nii.gz',
    'lung_upper_lobe_right.nii.gz',
    'pancreas.nii.gz',
    'portal_vein_and_splenic_vein.nii.gz',
    'prostate.nii.gz',
    'pulmonary_vein.nii.gz',
    'rib_left_10.nii.gz',
    'rib_left_11.nii.gz',
    'rib_left_12.nii.gz',
    'rib_left_1.nii.gz',
    'rib_left_2.nii.gz',
    'rib_left_3.nii.gz',
    'rib_left_4.nii.gz',
    'rib_left_5.nii.gz',
    'rib_left_6.nii.gz',
    'rib_left_7.nii.gz',
    'rib_left_8.nii.gz',
    'rib_left_9.nii.gz',
    'rib_right_10.nii.gz',
    'rib_right_11.nii.gz',
    'rib_right_12.nii.gz',
    'rib_right_1.nii.gz',
    'rib_right_2.nii.gz',
    'rib_right_3.nii.gz',
    'rib_right_4.nii.gz',
    'rib_right_5.nii.gz',
    'rib_right_6.nii.gz',
    'rib_right_7.nii.gz',
    'rib_right_8.nii.gz',
    'rib_right_9.nii.gz',
    'scapula_left.nii.gz',
    'scapula_right.nii.gz',
    'skull.nii.gz',
    'small_bowel.nii.gz',
    'spinal_cord.nii.gz',
    'spleen.nii.gz',
    'sternum.nii.gz',
    'stomach.nii.gz',
    'subclavian_artery_left.nii.gz',
    'subclavian_artery_right.nii.gz',
    'superior_vena_cava.nii.gz',
    'thyroid_gland.nii.gz',
    'trachea.nii.gz',
    'urinary_bladder.nii.gz',
    'vertebrae_C1.nii.gz',
    'vertebrae_C2.nii.gz',
    'vertebrae_C3.nii.gz',
    'vertebrae_C4.nii.gz',
    'vertebrae_C5.nii.gz',
    'vertebrae_C6.nii.gz',
    'vertebrae_C7.nii.gz',
    'vertebrae_L1.nii.gz',
    'vertebrae_L2.nii.gz',
    'vertebrae_L3.nii.gz',
    'vertebrae_L4.nii.gz',
    'vertebrae_L5.nii.gz',
    'vertebrae_S1.nii.gz',
    'vertebrae_T10.nii.gz',
    'vertebrae_T11.nii.gz',
    'vertebrae_T12.nii.gz',
    'vertebrae_T1.nii.gz',
    'vertebrae_T2.nii.gz',
    'vertebrae_T3.nii.gz',
    'vertebrae_T4.nii.gz',
    'vertebrae_T5.nii.gz',
    'vertebrae_T6.nii.gz',
    'vertebrae_T7.nii.gz',
    'vertebrae_T8.nii.gz',
    'vertebrae_T9.nii.gz'
]

MRI_SEG_FILE_LIST = [
    'adrenal_gland_left.nii.gz',
    'adrenal_gland_right.nii.gz',
    'aorta.nii.gz',
    'autochthon_left.nii.gz',
    'autochthon_right.nii.gz',
    'brain.nii.gz',
    'clavicula_left.nii.gz',
    'clavicula_right.nii.gz',
    'colon.nii.gz',
    'duodenum.nii.gz',
    'esophagus.nii.gz',
    'femur_left.nii.gz',
    'femur_right.nii.gz',
    'gallbladder.nii.gz',
    'gluteus_maximus_left.nii.gz',
    'gluteus_maximus_right.nii.gz',
    'gluteus_medius_left.nii.gz',
    'gluteus_medius_right.nii.gz',
    'gluteus_minimus_left.nii.gz',
    'gluteus_minimus_right.nii.gz',
    'heart.nii.gz',
    'hip_left.nii.gz',
    'hip_right.nii.gz',
    'humerus_left.nii.gz',
    'humerus_right.nii.gz',
    'iliac_artery_left.nii.gz',
    'iliac_artery_right.nii.gz',
    'iliac_vena_left.nii.gz',
    'iliac_vena_right.nii.gz',
    'iliopsoas_left.nii.gz',
    'iliopsoas_right.nii.gz',
    'inferior_vena_cava.nii.gz',
    'intervertebral_discs.nii.gz',
    'kidney_left.nii.gz',
    'kidney_right.nii.gz',
    'liver.nii.gz',
    'lung_left.nii.gz',
    'lung_right.nii.gz',
    'pancreas.nii.gz',
    'portal_vein_and_splenic_vein.nii.gz',
    'prostate.nii.gz',
    'sacrum.nii.gz',
    'scapula_left.nii.gz',
    'scapula_right.nii.gz',
    'small_bowel.nii.gz',
    'spinal_cord.nii.gz',
    'spleen.nii.gz',
    'stomach.nii.gz',
    'urinary_bladder.nii.gz',
    'vertebrae.nii.gz'
]

NAME_TO_LABEL_DICT = {
    'adrenal': 'adrenal gland',
    'adrenal_gland_left': 'adrenal gland',
    'adrenal_gland_left.nii.gz': 'adrenal gland',
    'adrenal_gland_right': 'adrenal gland',
    'adrenal_gland_right.nii.gz': 'adrenal gland',
    'aneurysm': 'aneurysm',
    'aorta': 'aorta',
    'aorta.nii.gz': 'aorta',
    'atrial_appendage_left.nii.gz': 'atrial appendage',
    'autochthon_left.nii.gz': 'autochthon',
    'autochthon_right.nii.gz': 'autochthon',
    # 'background': 'background',
    'bladder': 'bladder',
    'brachiocephalic_trunk.nii.gz': 'brachiocephalic trunk',
    'brachiocephalic_vein_left.nii.gz': 'brachiocephalic vein',
    'brachiocephalic_vein_right.nii.gz': 'brachiocephalic vein',
    'brain': 'brain',
    'brain.nii.gz': 'brain',
    'brainstem': 'brainstem',
    'breast_tumor': 'breast tumor',
    'clavicula_left.nii.gz': 'clavicula',
    'clavicula_right.nii.gz': 'clavicula',
    'cochlea_left': 'cochlea',
    'cochlea_right': 'cochlea',
    'colon': 'colon',
    'colon.nii.gz': 'colon',
    'common_carotid_artery_left.nii.gz': 'common carotid artery',
    'common_carotid_artery_right.nii.gz': 'common carotid artery',
    'costal_cartilages.nii.gz': 'costal cartilages',
    'duodenum': 'duodenum',
    'duodenum.nii.gz': 'duodenum',
    'edema': 'edema',
    'enhancing_tumor': 'enhancing tumor',
    'esophagus': 'esophagus',
    'esophagus.nii.gz': 'esophagus',
    'eustachian_tube_left': 'eustachian tube',
    'eustachian_tube_right': 'eustachian tube',
    'eye_left': 'eye',
    'eye_right': 'eye',
    'femur_left.nii.gz': 'femur',
    'femur_right.nii.gz': 'femur',
    'gallbladder': 'gallbladder',
    'gallbladder.nii.gz': 'gallbladder',
    'glioma': 'glioma',
    'gluteus_maximus_left.nii.gz': 'gluteus maximus',
    'gluteus_maximus_right.nii.gz': 'gluteus maximus',
    'gluteus_medius_left.nii.gz': 'gluteus medius',
    'gluteus_medius_right.nii.gz': 'gluteus medius',
    'gluteus_minimus_left.nii.gz': 'gluteus minimus',
    'gluteus_minimus_right.nii.gz': 'gluteus minimus',
    'head_of_femur_left': 'head of femur',
    'head_of_femur_right': 'head of femur',
    'heart.nii.gz': 'heart',
    'heart_ascending_aorta': 'heart ascending aorta',
    'heart_atrium_left': 'heart atrium',
    'heart_left_atrium_blood_cavity': 'heart left atrium blood cavity',
    'heart_left_ventricle_blood_cavity': 'heart left ventricle blood cavity',
    'heart_left_ventricular_myocardium': 'heart ventricular myocardium',
    'heart_myocardium': 'heart myocardium',
    'heart_myocardium_left': 'heart myocardium',
    'heart_right_atrium_blood_cavity': 'heart right atrium blood cavity',
    'heart_right_ventricle_blood_cavity': 'heart right ventricle blood cavity',
    'heart_ventricle_left': 'heart ventricle',
    'heart_ventricle_right': 'heart ventricle',
    'hip_left.nii.gz': 'hip',
    'hip_right.nii.gz': 'hip',
    'hippocampus_left': 'hippocampus',
    'hippocampus_right': 'hippocampus',
    'humerus_left.nii.gz': 'humerus',
    'humerus_right.nii.gz': 'humerus',
    'iliac_artery_left.nii.gz': 'iliac artery',
    'iliac_artery_right.nii.gz': 'iliac artery',
    'iliac_vena_left.nii.gz': 'iliac vena',
    'iliac_vena_right.nii.gz': 'iliac vena',
    'iliopsoas_left.nii.gz': 'iliopsoas',
    'iliopsoas_right.nii.gz': 'iliopsoas',
    'inferior_vena_cava': 'inferior vena cava',
    'inferior_vena_cava.nii.gz': 'inferior vena cava',
    'internal_auditory_canal_left': 'internal auditory canal',
    'internal_auditory_canal_right': 'internal auditory canal',
    'intervertebral_discs.nii.gz': 'intervertebral discs',
    'intestine': 'intestine',
    'kidney': 'kidney',
    'kidney_cyst': 'kidney cyst',
    'kidney_cyst_left.nii.gz': 'kidney cyst',
    'kidney_cyst_right.nii.gz': 'kidney cyst',
    'kidney_left': 'kidney',
    'kidney_left.nii.gz': 'kidney',
    'kidney_right': 'kidney',
    'kidney_right.nii.gz': 'kidney',
    'kidney_tumor': 'kidney tumor',
    'larynx': 'larynx',
    'larynx_glottic': 'larynx glottic',
    'larynx_supraglot': 'larynx supraglot',
    'left_ventricular_blood_pool': 'left ventricular blood pool',
    'left_ventricular_myocardial_edema': 'left ventricular myocardial edema',
    'left_ventricular_myocardial_scars': 'left ventricular myocardial scars',
    'left_ventricular_normal_myocardium': 'left ventricular normal myocardium',
    'lens_left': 'lens',
    'lens_right': 'lens',
    'liver': 'liver',
    'liver.nii.gz': 'liver',
    'liver_tumor': 'liver tumor',
    'lung': 'lung',
    'lung_infections': 'lung infections',
    'lung_left': 'lung',
    'lung_left.nii.gz': 'lung',
    'lung_lower_lobe_left.nii.gz': 'lung lower lobe',
    'lung_lower_lobe_right.nii.gz': 'lung lower lobe',
    'lung_middle_lobe_right.nii.gz': 'lung middle lobe',
    'lung_right': 'lung',
    'lung_right.nii.gz': 'lung',
    'lung_upper_lobe_left.nii.gz': 'lung upper lobe',
    'lung_upper_lobe_right.nii.gz': 'lung upper lobe',
    'lung_vessel': 'lung',
    'mandible_left': 'mandible',
    'mandible_right': 'mandible',
    'mastoid_left': 'mastoid',
    'mastoid_right': 'mastoid',
    'middleear_left': 'middleear',
    'middleear_right': 'middleear',
    'myocardial_infarction': 'myocardial infarction',
    'necrosis': 'necrosis',
    'necrotic_tumor_core': 'necrotic tumor core',
    'neuroblastoma': 'neuroblastoma',
    'no_reflow': 'no reflow',
    'non_enhancing_tumor': 'non enhancing tumor',
    'optic_chiasm': 'optic chiasm',
    'optic_cup': 'optic cup',
    'optic_disc': 'optic disc',
    'optic_nerve_left': 'optic nerve',
    'optic_nerve_right': 'optic nerve',
    'oral_cavity': 'oral cavity',
    'pancreas': 'pancreas',
    'pancreas.nii.gz': 'pancreas',
    'parotid_left': 'parotid',
    'parotid_right': 'parotid',
    'peritumoral_edema': 'peritumoral edema',
    'pharynx': 'pharynx',
    'pituitary': 'pituitary',
    'pleural_effusion': 'pleural effusion',
    'polyp': 'polyp',
    'portal_vein': 'portal vein',
    'portal_vein_and_splenic_vein': 'portal vein and splenic vein',
    'portal_vein_and_splenic_vein.nii.gz': 'portal vein and splenic vein',
    'prostate': 'prostate',
    'prostate.nii.gz': 'prostate',
    'prostate_and_uterus': 'prostate and uterus',
    'prostate_anterior_fibromuscular_stroma': 'prostate anterior fibromuscular stroma',
    'prostate_peripheral_zone': 'prostate peripheral zone',
    'prostate_transition_zone': 'prostate transition zone',
    'prostatic_urethra': 'prostatic urethra',
    'pulmonary_artery': 'pulmonary artery',
    'pulmonary_vein.nii.gz': 'pulmonary vein',
    'rectum': 'rectum',
    'rib_left_1.nii.gz': 'rib',
    'rib_left_10.nii.gz': 'rib',
    'rib_left_11.nii.gz': 'rib',
    'rib_left_12.nii.gz': 'rib',
    'rib_left_2.nii.gz': 'rib',
    'rib_left_3.nii.gz': 'rib',
    'rib_left_4.nii.gz': 'rib',
    'rib_left_5.nii.gz': 'rib',
    'rib_left_6.nii.gz': 'rib',
    'rib_left_7.nii.gz': 'rib',
    'rib_left_8.nii.gz': 'rib',
    'rib_left_9.nii.gz': 'rib',
    'rib_right_1.nii.gz': 'rib',
    'rib_right_10.nii.gz': 'rib',
    'rib_right_11.nii.gz': 'rib',
    'rib_right_12.nii.gz': 'rib',
    'rib_right_2.nii.gz': 'rib',
    'rib_right_3.nii.gz': 'rib',
    'rib_right_4.nii.gz': 'rib',
    'rib_right_5.nii.gz': 'rib',
    'rib_right_6.nii.gz': 'rib',
    'rib_right_7.nii.gz': 'rib',
    'rib_right_8.nii.gz': 'rib',
    'rib_right_9.nii.gz': 'rib',
    'right_ventricular_blood_pool': 'ventricular blood pool',
    'sacrum.nii.gz': 'sacrum',
    'scapula_left.nii.gz': 'scapula',
    'scapula_right.nii.gz': 'scapula',
    'skin_lesion': 'skin lesion',
    'skull.nii.gz': 'skull',
    'small_bowel.nii.gz': 'small bowel',
    'spinal_cord': 'spinal cord',
    'spinal_cord.nii.gz': 'spinal cord',
    'spleen': 'spleen',
    'spleen.nii.gz': 'spleen',
    'sternum.nii.gz': 'sternum',
    'stomach': 'stomach',
    'stomach.nii.gz': 'stomach',
    'subclavian_artery_left.nii.gz': 'subclavian artery',
    'subclavian_artery_right.nii.gz': 'subclavian artery',
    'submandibular_left': 'submandibular',
    'submandibular_right': 'submandibular',
    'superior_vena_cava.nii.gz': 'superior vena cava',
    'temporal_lobe_left': 'temporal lobe',
    'temporal_lobe_right': 'temporal lobe',
    'temporomandibular_joint_left': 'temporomandibular joint',
    'temporomandibular_joint_right': 'temporomandibular joint',
    'thoracic_cavity': 'thoracic cavity',
    'thyroid': 'thyroid',
    'thyroid_gland.nii.gz': 'thyroid gland',
    'trachea': 'trachea',
    'trachea.nii.gz': 'trachea',
    'treated_aneurysm': 'treated aneurysm',
    'tympanic_cavity_left': 'tympanic cavity',
    'tympanic_cavity_right': 'tympanic cavity',
    'urinary_bladder.nii.gz': 'urinary bladder',
    'vertebrae.nii.gz': 'vertebrae',
    'vertebrae_C1.nii.gz': 'vertebrae',
    'vertebrae_C2.nii.gz': 'vertebrae',
    'vertebrae_C3.nii.gz': 'vertebrae',
    'vertebrae_C4.nii.gz': 'vertebrae',
    'vertebrae_C5.nii.gz': 'vertebrae',
    'vertebrae_C6.nii.gz': 'vertebrae',
    'vertebrae_C7.nii.gz': 'vertebrae',
    'vertebrae_L1.nii.gz': 'vertebrae',
    'vertebrae_L2.nii.gz': 'vertebrae',
    'vertebrae_L3.nii.gz': 'vertebrae',
    'vertebrae_L4.nii.gz': 'vertebrae',
    'vertebrae_L5.nii.gz': 'vertebrae',
    'vertebrae_S1.nii.gz': 'vertebrae',
    'vertebrae_T1.nii.gz': 'vertebrae',
    'vertebrae_T10.nii.gz': 'vertebrae',
    'vertebrae_T11.nii.gz': 'vertebrae',
    'vertebrae_T12.nii.gz': 'vertebrae',
    'vertebrae_T2.nii.gz': 'vertebrae',
    'vertebrae_T3.nii.gz': 'vertebrae',
    'vertebrae_T4.nii.gz': 'vertebrae',
    'vertebrae_T5.nii.gz': 'vertebrae',
    'vertebrae_T6.nii.gz': 'vertebrae',
    'vertebrae_T7.nii.gz': 'vertebrae',
    'vertebrae_T8.nii.gz': 'vertebrae',
    'vertebrae_T9.nii.gz': 'vertebrae',
    'vestibular_semicircular_canal_left': 'vestibular semicircular canal',
    'vestibular_semicircular_canal_right': 'vestibular semicircular canal',
}

MODALITY_NAME_TO_LABEL_DICT = {
    'CT': 'CT',
    'mr_t1gd': 'T1w-Gd MRI',
    'x_ray': 'x-ray',
    'mr_cmr': 'cardiac MRI',
    'dermoscopy': 'dermoscopy',
    'ct': 'CT',
    'mr_flair': 'FLAIR MRI',
    'mr': 'MRI',
    'MRI': 'MRI',
    'mr_tof': 'TOF MRA',
    'mr_t2w': 'T2w MRI',
    'MR_T2w': 'T2w MRI',
    'us': 'ultrasound',
    'mr_unknown': 'MRI',
    'MR': 'MRI',
    'endoscopy': 'endoscopy',
    'fundus_photography': 'fundus photography',
    'mr_t1w': 'T1w MRI',
    'mr_t2': 'T2w MRI',
}
